### ISSUE TITLE
Possible race condition when adding claim blocks

### ISSUE THREAD

**Issue by ProdPreva1l** [WiIIiam278/HuskClaims#100]
Seems that when adding claims bocks with the command in quick succession it fails and reverts back to previous before adding them again

![image](https://github.com/WiIIiam278/HuskClaims/assets/149850944/b22e7dd0-7b2d-42cc-ada5-42d2ecf547b9)

**Comment by WiIIiam278** [comment]
hmm yeah may need to queue those? Strange though as I think this should use a concurrentmap internally

**Comment by WiIIiam278** [comment]
Closed by #108
