### ISSUE TITLE
Add more information about claim block expenditure to /claimblocks

### ISSUE THREAD

**Issue by Cytosta** [WiIIiam278/HuskClaims#102]
Right now the way to check someone's claimblocks is via /claimblocks <playername> and it'll return their remaining claimblocks. But there's no way to see how many claimblocks they've used, what their total was, how many they've received from hourly play, or from manually being added, etc. From an administration perspective, all of those are helpful to know when checking someone. There is the /claimslist <playername> which shows all of their claims, locations, size, and claimblocks used - but you'd have to currently add up all of the claimblocks from their current claims and add their remaining claimblocks to get their total.

What I'd love to see from /playerinfo <playername> (which would also be a default player command without the <playername> arg, to see their own stats)

Total Claims;
Used/Remaining/Total Claimblocks;
Accrued Blocks (amount you've gotten from playtime/hourly);
Initial Blocks (the amount you started with);
Bonus Blocks (the amount that has been added to you via /claimblocks <player> add <amount>.

**Comment by WiIIiam278** [comment]
After some thought, I've decided that this would be better served by adding this information to `/claimblock` :)
