### ISSUE TITLE
Wilderness check errors are too verbose

### ISSUE THREAD

**Issue by Gingied** [WiIIiam278/HuskClaims#105]
Purpur 1.20.4
Velocity 3.3.0
Here are a things I have noticed since the release of 1.2, after which I altered my wilderness flags in one of my servers.

- The "You are not allowed to do that in the wilderness" deny messages are not exclusive of the plugin's other deny messages: When attempting to violate flags in the wilderness this message appears as intended. But when interacting with a claim in a way which violates wilderness flags (e.g. build in my case), the "You are not allowed to do that in the wilderness" message is shown regardless of trust level or the player's permission to interact there, and in addition to other messages like "that land is protected by Player claim."

- When build permission is denied in the wilderness, rightclicking with air (empty) in hand also triggers the deny message.

**Comment by WiIIiam278** [comment]
Unable to reproduce this on the latest release, please attempt to do so with some more detailed steps / a video
