### ISSUE TITLE
Add Worldguard support

### ISSUE THREAD

**Issue by Gingied** [WiIIiam278/HuskClaims#107]
I think some (my) servers would benefit from having a simple config toggle for worldguard support. Could be a binary huskclaims allowed in WG regions / not allowed. For regions where huskclaims is not allowed, claims could not be created which overlap these areas, huskclaims' flags don't take effect, etc.

Alternatively, for more flexibility, the toggle could enable the use of huskclaims.region.<regionName> permissions for enabling/disabling claims in specific zones.

ETA: I know this is a much larger ask, but support for worldedit as a flag so that I can use HuskClaims for creative would be amazing

**Comment by WiIIiam278** [comment]
As with HuskTowns, we're gonna implement a new hook system to make this better :)
