### ISSUE TITLE
Ability to silentely check if an operation is allowed

### ISSUE THREAD

**Issue by timderspieler** [WiIIiam278/HuskClaims#122]
Hello,

I am currently adding support for HuskClaims to my plugin.
First, I'd like to mention that the documentation is excellent. It was really easy to understand which method calls I have to use in order to implement the functionality I'd like to have. Thumbs up for that!

While testing my implementation I noticed one small bug?/issue?/annoying thing? (whatever you want to call it): Each time I call the huskClaimsAPI.isOperationAllowed method, the user which executes the operation receives a message in case he is not allowed to perform it.

That message would be okay if I call this method once at a time, but for my usecase I have to call this method X-times when a player moves (region barriers).

Therefore I'd like to request a flag you can set whether you want a message to be printed or not when checking if an operation is not allowed.

Thank you very much!

Here is my code:
```
    public boolean canPvP(Player player, Location location) {
        OnlineUser user = huskClaimsAPI.getOnlineUser(player);
        Position position = huskClaimsAPI.getPosition(location);
        if (user == null || position == null) {
            return true;
        }
        return huskClaimsAPI.isOperationAllowed(user, OperationType.PLAYER_DAMAGE_PLAYER, position);
    }
```

Thats the chat output for me:
![grafik](https://github.com/WiIIiam278/HuskClaims/assets/19387835/d8408f25-657d-438e-875b-8f1aefd495f0)

**Comment by WiIIiam278** [comment]
Howdy,

You'll want to use the method that accepts an Operation that you've set to be `silent`.

To make a silent operation:
```java
// The fourth arg here sets the Operation to silent.
Operation silentOperation = Operation.of(user, OperationType.PLAYER_DAMAGE_PLAYER, position, true);
```

Then just pass it:
```java
boolean isAllowed = huskClaimsAPI.isOperationAllowed(silentOperation);
```

**Comment by WiIIiam278** [comment]
Anytime :)
