### ISSUE TITLE
feature request: claim fly

### ISSUE THREAD

**Issue by Ibotmealot** [WiIIiam278/HuskClaims#139]
similar to a feature that the [lands plugin](https://www.spigotmc.org/resources/lands-⭕-land-claim-plugin-✅-grief-prevention-protection-gui-management-nations-wars-1-21-support.53313/) offers, the ability to allow users to fly in their own claim with a permission node (or others with a different perm). 

this feature would also preferably have some config options similar to lands (see [here](https://github.com/Angeschossen/Lands/blob/main/config.yml#L408)). 

there are also [plugins like this for grief prevention](https://github.com/weaves7/ClaimFly/tree/v1.3.0 ), but I couldn't find anything for husk claims.

**Comment by ProdPreva1l** [comment]
This plugin will work https://www.spigotmc.org/resources/choco-fly-1-20-x.95180/

**Comment by Ibotmealot** [comment]
> This plugin will work https://www.spigotmc.org/resources/choco-fly-1-20-x.95180/

oh, neat, I'll give this a try; thank you! 😄

**Comment by WiIIiam278** [comment]
Closing in favor of an external plugin ^^

**Comment by Yurkhun** [comment]
> Closing in favor of an external plugin ^^

to be honest chocofly works horribly, fly keep working when players get out of the claim, would be nice this feature to be build-in to not happen bugs like that
