### ISSUE TITLE
Usernames Not Updating Automatically After Username Change

### ISSUE THREAD

**Issue by Patrickmid7** [WiIIiam278/HuskClaims#149]
We have identified a bug where a user's new username is not updated automatically after they change it. Instead, the system still thinks their old username is correct. 
This issue was discovered during a test where a user changed their Minecraft username from `IkBenNietZwaa` to `__Kwik__`. 
When using `/trust __Kwik__` we got an error: "This user is not found", and when using the player's old username with `/trust IkBenNietZwaa` the user __Kwik__ got access to the claim. Only admins are able to trust old usernames, because the other players get an error: "This user is currently offline".

Despite the new username not being recognized when trusted on a claim, the old username does work and also appears in the trust list.

It should be working with the new username only.

**Comment by JorisvD01** [comment]
I'm experiencing the same issue as described above ^
Using version 1.3.3-931ff98
