### ISSUE TITLE
Possibility to make a claim private

### ISSUE THREAD

**Issue by Patrickmid7** [WiIIiam278/HuskClaims#157]
Feature request:

I would like to see an option to make my claim private, so that no-one can enter the claim except for the owner and trustees.
Basically a 'ban-all-from-claim'.

The best way would probably be via a toggle command. `/claim private true` or `/claim private false` for example.

Also please add a permission to assign to staff to bypass this feature.

**Comment by WiIIiam278** [comment]
Closed by #174
