### ISSUE TITLE
Banning a user ignoring claims will still remove them from the claim

### ISSUE THREAD

**Issue by Patrickmid7** [WiIIiam278/HuskClaims#167]
Currently a user has the ability to ban a staff-member from their claim using the /claimban command.
The staff-member can still fly back into the claim, however will be teleported outside the claim each time the user executes the command.

I would assume that users/ranks with the `huskclaims.command.ignoreclaims` would also be invulnerable for claimbans.

**Comment by WiIIiam278** [comment]
Please attempt to walk into a claim you have been banned on while `/ignoreclaims` is active. It should allow you in, despite being banned. Can you confirm this is the case?

**Comment by Patrickmid7** [comment]
We have tested this and yes, you are able to walk back into the claim, while `/ignoreclaims` is active. However it is annoying when the claim-owner keeps banning the staff over and over again so they get teleported outside the claim every time.

**Comment by WiIIiam278** [comment]
I see, so to clarify while `/ignoreclaim` is active players are still _kicked out_ of claims when banned, but can walk _into_ them just fine?

**Comment by Patrickmid7** [comment]
> I see, so to clarify while `/ignoreclaim` is active players are still _kicked out_ of claims when banned, but can walk _into_ them just fine?

Correct!

**Comment by WiIIiam278** [comment]
Fixed by https://github.com/WiIIiam278/HuskClaims/commit/0c616ef229d89dda602a73524a4192bc1e78aed1
