### ISSUE TITLE
Ability to enter a players' claim while being banned.

### ISSUE THREAD

**Issue by Patrickmid7** [WiIIiam278/HuskClaims#168]
When using the /sit command from [Gsit](https://www.spigotmc.org/resources/gsit-modern-sit-seat-and-chair-lay-and-crawl-plugin-1-16-1-21-1.62325/) next to a claim while being banned from the claim, and standing back up. There is a chance that you will be inside the claim, even though you're banned. Once you're in there isn't any check anymore, so you can just do whatever you fancy.

Besides the above problem, it's also possible to break Minecarts inside a claim where you don't have trust. It looks like the Minecarts bypass all 'Allowed Operations'.

**Comment by WiIIiam278** [comment]
Could you attach a video to demonstrate your first issue, making sure you have been banned from the claim?

Please create a separate issue for your second, unrelated issue.

**Comment by Patrickmid7** [comment]
Please have a look at [this video](https://www.youtube.com/watch?v=VUMwDmG7RnQ);

It took a couple of tries, but the user '_Pink_Punda_' has been banned from Elinaatjes claim but still was able to enter.
It seems to be working when crouching really close to the claims' edge and than sitting, it will put the player inside the claim.
