### ISSUE TITLE
[BUG and corresponding solutions] Players can claim land within the territory of Husktowns.

### ISSUE THREAD

**Issue by MSCMDD** [WiIIiam278/HuskClaims#188]
BUG: Players can claim land within the territory of Husktowns.
Feature Request: Prevent players from declaring land in Husktowns' Claims, and transfer the management of Husktowns' Plot territories to HuskClaims when designated to a specific Member.

**Comment by WiIIiam278** [comment]
My main intent is that you use EITHER HuskClaims or HuskTowns and not both. However, the two should work together and there is a feature built-in to HuskClaims to restrict creation of HuskTowns claims in HuskClaims claims (not vice-versa, however). I will close this request for now as this is a matter on that side - please create a support ticket in Discord if the former specifically is not working.

**Comment by MSCMDD** [comment]
Although I personally believe that the Husk series plugins should have a higher degree of compatibility with fellow author plugins, perhaps this is a problem with the roadmap
Thank you for answering this issue

在 2024年9月6日，23:29，William ***@***.******@***.***>> 写道：


My main intent is that you use EITHER HuskClaims or HuskTowns and not both. However, the two should work together and there is a feature built-in to HuskClaims to restrict creation of HuskTowns claims in HuskClaims claims (not vice-versa, however). I will close this request for now as this is a matter on that side - please create a support ticket in Discord if the former specifically is not working.
