### ISSUE TITLE
Tamed Dmg & Tamed Interact console spam?

### ISSUE THREAD

**Issue by Blackberrii** [WiIIiam278/HuskClaims#191]
I'm using version 1.4 of HuskClaims and I'm not entirely sure why this message keeps spamming the console

![image](https://github.com/user-attachments/assets/1452d102-6137-4fb6-9625-f1f198940be1)

my server is running Purpur 1.21.1, there is no errors before or following the startup, disabling or running of the plugin just this message when people interact with entities.

If this is some sort of configuration issue I sincerely apologize ahead of time.
I have also attached my config file below just in case it is some sort of error on my end.
Thank you!
[config.zip](https://github.com/user-attachments/files/17070500/config.zip)

**Comment by ProdPreva1l** [comment]
Use latest alpha version on https://william278.net/

**Comment by Blackberrii** [comment]
> Use latest alpha version on https://william278.net/

Thanks for the quick reply!
I'll get verified in the discord and try it out I appreciate it

**Comment by WiIIiam278** [comment]
Already fixed in #187
