### ISSUE TITLE
HuskHomes hook is failing to protect against sethome on claims where users don't have access

### ISSUE THREAD

**Issue by xsorencoolx** [WiIIiam278/HuskClaims#210]
https://github.com/user-attachments/assets/8a4387f3-04d0-4d84-b363-142430b3fc65

**Comment by WiIIiam278** [comment]
Unable to repro in latest version

**Comment by WiIIiam278** [comment]
Please attach a screenshot of /huskclaims status and your version of huskclaims and startup logs
