### ISSUE TITLE
Bedrock support not working

### ISSUE THREAD

**Issue by OakLoaf** [WiIIiam278/HuskClaims#234]
It appears as though, even with the new geyser feature, bedrock players cannot see the border of their claims. We are using Geyser Standalone and we have Floodgate on the server

**Comment by WiIIiam278** [comment]
Is geyser mode enabled and running? Screenshot /husksync status

**Comment by OakLoaf** [comment]
No mention of Geyser in the status command, the server has restarted at least once or twice since the config change.
```
• Registered Highlighters: BlockDisplayHighlighter, BlockUpdateHighlighter
• Loaded Hooks: PlaceholderAPI, LuckPerms, Vault, Plan, WorldGuard
• Loaded Importers: GriefPrevention
```

```
  geyser:
    # Whether to hook into Geyser to ensure Bedrock users can see claim highlights
    enabled: true
```

**Comment by OakLoaf** [comment]
Would that be in the logs?

**Comment by WiIIiam278** [comment]
If the hook were activated it would appear in the status screen; it hasn't, meaning something's going wrong with the actual enabling of the hook.

**Comment by OakLoaf** [comment]
I have just tested this on the latest dev build ce87144 and the same issue is occurring:

```
