### ISSUE TITLE
Non-trustees can break minecarts within a claim

### ISSUE THREAD

**Issue by ColdSight** [WiIIiam278/HuskClaims#242]
**Version:** 1.4.4

As in what the title says non-trustees of a claim can break a minecart (works with chest minecarts as well, etc).

**Comment by WiIIiam278** [comment]
Could you please provide:
- - a video of this occurring, showing the action of the minecart breaking and the trust list in the claim 
- your trust levels config file
- your config file

**Comment by djoey123** [comment]
Video: https://youtu.be/4KLbPxC-bi0

Default config / Trust level config

Did already some debugging.

When minecart is hit, is doesnt show up on:
ClaimWorld::isOperationAllowed

This problem is also on Boats / Boats with chests

**Comment by WiIIiam278** [comment]
Better handling for vehicles was needed and has been added to the upstream library in the form of two new operation types: VEHICLE_PLACE and VEHICLE_BREAK. For container vehicles (boat with chest), I have moved breaking these to BLOCK_BREAK/PLACE and added the container check when interacting.
