### ISSUE TITLE
Vehicle place issues when updating to 1.4.5

### ISSUE THREAD

**Issue by OakLoaf** [WiIIiam278/HuskClaims#271]
After updating my `trust_levels.yml` and restarting the server, players cannot place vehicles, I own this claim but the same is occurring for people with build trust.

My `allowed_owner_operations` list is the following:
```
allowed_owner_operations:
- FARM_BLOCK_PLACE
- BREAK_HANGING_ENTITY
- FARM_BLOCK_BREAK
- PLAYER_DAMAGE_MONSTER
- ENTITY_INTERACT
- BREAK_VEHICLE
- FARM_BLOCK_INTERACT
- BLOCK_PLACE
- REDSTONE_INTERACT
- START_RAID
- PLAYER_DAMAGE_ENTITY
- BLOCK_INTERACT
- PLACE_HANGING_ENTITY
- PLACE_VEHICLE
- CONTAINER_OPEN
- EMPTY_BUCKET
- FILL_BUCKET
- USE_SPAWN_EGG
- BLOCK_BREAK
- PLAYER_DAMAGE_PLAYER
- ENDER_PEARL_TELEPORT
- PLAYER_DAMAGE_PERSISTENT_ENTITY
```

This is a video of the issue
https://github.com/user-attachments/assets/9bb44ece-bd8d-40bf-b759-1216a69cd694

**Comment by WiIIiam278** [comment]
This was due to a bug which I have subsequently already fixed. You can update to the latest alpha, or wait for the next release version. Also, tip: make sure you've stood in your wilderness and used /claimflags to add the flags to your wilderness.
