### ISSUE TITLE
Ability to be more specifc with claim tools

### ISSUE THREAD

**Issue by TypicalShavonne** [WiIIiam278/HuskClaims#49]
Only perform claim checking on PlayerInteractEvent with a stick when the player is holding a normal stick with no custom NBTs, enchantments, lore, custom name
Im getting conflict with itemsadder and sellwands plugin because of that

**Comment by WiIIiam278** [comment]
You can change the item type in config but I guess we can look at adding some more restrictions on the exact usable item
