### ISSUE TITLE
Add way of changing wilderness flags in a claim world

### ISSUE THREAD

**Issue by RustyDagger** [WiIIiam278/HuskClaims#94]
Changing them seems to have no effect on the wilderness Iv removed both build and place flags and everyone can still build and place.

Huskclaims: v1.1.2
paper: git-Paper-462

plugins:
Server Plugins (24):
Paper Plugins:
 - HuskClaims
Bukkit Plugins:
- BetterStructures, Chunky, CMI, CMILib, EnchantmentForge, FastAsyncWorldEdit, HeadDatabase, ItemsAdder, JetsRepairTokens, LiteFarm
LiteFish, LiteMatter, LoneLibs, LuckPerms, Multiverse-Core, ParadiseLand, PlaceholderAPI, ProtocolLib, SelectionVisualizer, Vault
WorldGuard, XenoWorldReset, zMenu

other things of note:

The world with the issues is a world with a custom gen from ParadiseLand its named skyisland.
Servers been restarted several times since changes were made No one is Op and iv used lp verbose to make sure iv not got any perms bypassing anything.

**Comment by WiIIiam278** [comment]
Right, so here's the underlying issue - and it's an oversight on my part: Wilderness flags are persisted - that config section only changes the _default_ flags of Wilderness in claim worlds.

There needs to be a way of changing these flags after claim world creation; hence, I'm changing this to a feature request and will be updating the docs.
